NAME: TRAFFIC SIPHON MONITOR

ON:
  SCHEDULE:
    - CRON: '*/30 * * * *'
  WORKFLOW_DISPATCH:

JOBS:
  MONITOR:
    RUNS-ON: UBUNTU-LATEST
    PERMISSIONS:
      CONTENTS: WRITE
    STEPS:
      - USES: ACTIONS/CHECKOUT@V3
      
      - NAME: SET UP PYTHON
        USES: ACTIONS/SETUP-PYTHON@V4
        WITH:
          PYTHON-VERSION: '3.9'
          
      - NAME: RUN TRAFFIC-SIPHON
        RUN: PYTHON3 TRAFFIC-SIPHON.PY --URL "HTTPS://DONABICO-GLOBAL-MEDIA.GITHUB.IO/8000KICKS/"
        
      - NAME: COMMIT RESULT
        RUN: |
          GIT CONFIG USER.NAME "SIPHON BOT"
          GIT CONFIG USER.EMAIL "BOT@GITHUB.COM"
          GIT ADD TRAFFIC_REPORT.JSON
          GIT COMMIT -M "UPDATE TRAFFIC REPORT"
          GIT PUSH
